import { asset } from "@/lib/data";

export const WORK = [
  {
    name: "Knotfest",
    tag: ["BOH Management, Nationwide"],
    img: asset("/assets/work-knotfest.jpg"),
    logo: asset("/assets/client-knotfest.webp"),
    logoWidth: 200,
    logoHeight: 28,
  },
  {
    name: "Good Things Festival",
    tag: ["BOH Management, Nationwide", "Retail Precinct Management"],
    img: asset("/assets/work-good-things.jpg"),
    logo: asset("/assets/client-good-things.svg"),
    logoWidth: 180,
    logoHeight: 45,
  },
  {
    name: "Beyond The Valley",
    tag: ["Retail Precinct Management"],
    img: asset("/assets/work-beyond-the-valley.jpg"),
    logo: asset("/assets/client-beyond-the-valley.svg"),
    logoWidth: 170,
    logoHeight: 21,
  },
  {
    name: "A3 Festival",
    tag: [
      "Artist Services",
      "Volunteer Management",
      "Front Gate Management",
      "Box Office Management",
      "Accreditation",
    ],
    img: asset("/assets/work-a3.jpg"),
    logo: asset("/assets/client-a3.webp"),
    logoWidth: 156,
    logoHeight: 32,
  },
  {
    name: "Let Them Eat Cake",
    tag: ["Artist Services", "Industry Ticketing / Community Building"],
    img: asset("/assets/work-let-them-eat-cake.jpg"),
    logo: asset("/assets/client-let-them-eat-cake.svg"),
    logoWidth: 144,
    logoHeight: 27,
  },
  {
    name: "Promiseland",
    tag: [
      "Artist Services",
      "Industry Ticketing / Community Building",
      "Retail Precinct Management",
    ],
    img: asset("/assets/work-promiseland.jpg"),
    logo: asset("/assets/client-promiseland.webp"),
    logoWidth: 213,
    logoHeight: 97,
  },
  {
    name: "Eden Festival (NZ)",
    tag: ["Artist Services"],
    img: asset("/assets/work-eden-fest.jpg"),
    logo: asset("/assets/client-eden-fest.webp"),
    logoWidth: 256,
    logoHeight: 89,
  },
  {
    name: "Souled Out",
    tag: ["Artist Services"],
    img: asset("/assets/work-souled-out.jpg"),
    logo: asset("/assets/client-souled-out.webp"),
    logoWidth: 286,
    logoHeight: 99,
  },
  {
    name: "Happy Hour",
    tag: ["End-to-end Event Delivery, Nationwide"],
    img: asset("/assets/work-happy-hour.jpg"),
    logo: asset("/assets/client-happy-hour.webp"),
    logoWidth: 245,
    logoHeight: 64,
  },
  {
    name: "Our City Our Sound",
    tag: ["Artist Services", "Box Office", "Accreditation"],
    img: asset("/assets/work-our-city-our-sound.jpg"),
    logo: asset("/assets/client-our-city-our-sound.svg"),
    logoWidth: 108,
    logoHeight: 77,
  },
  {
    name: "Pitch Music and Arts",
    tag: [
      "Industry Ticketing / Community Building",
      "Retail Precinct Management",
    ],
    img: asset("/assets/work-pitch.jpg"),
    logo: asset("/assets/client-pitch.webp"),
    logoWidth: 193,
    logoHeight: 68,
  },
  {
    name: "Strummingbird",
    tag: ["Artist Services, Nationwide"],
    img: asset("/assets/work-strummingbird.jpg"),
    logo: asset("/assets/client-strummingbird.svg"),
    logoWidth: 168,
    logoHeight: 35,
  },
  {
    name: "Chapter",
    tag: ["End-to-end Event Delivery"],
    img: asset("/assets/work-chapter.jpg"),
    logo: asset("/assets/client-chapter.webp"),
    logoWidth: 182,
    logoHeight: 85,
  },
  {
    name: "Strawberry Fields",
    tag: ["Industry Ticketing / Community Building"],
    img: asset("/assets/work-strawberry-fields.jpg"),
    logo: asset("/assets/client-strawberry-fields.webp"),
    logoWidth: 241,
    logoHeight: 57,
  },
  {
    name: "Afrosoul",
    tag: ["Industry Ticketing / Community Building"],
    img: asset("/assets/work-afrosoul.jpg"),
    logo: asset("/assets/client-afrosoul.svg"),
    logoWidth: 185,
    logoHeight: 55,
  },
  {
    name: "Live Nation",
    tag: ["Industry Ticketing / Community Building"],
    img: asset("/assets/work-live-nation.jpg"),
    logo: asset("/assets/client-live-nation.webp"),
    logoWidth: 214,
    logoHeight: 53,
  },
  {
    name: "Astral People",
    tag: ["Industry Ticketing / Community Building"],
    img: asset("/assets/work-astral-people.jpg"),
    logo: asset("/assets/client-astral-people.svg"),
    logoWidth: 98,
    logoHeight: 69,
  },
  {
    name: "S.A.S.H",
    tag: ["Artist Advancing, Nationwide"],
    img: asset("/assets/work-sash.jpg"),
    logo: asset("/assets/client-sash.svg"),
    logoWidth: 180,
    logoHeight: 45,
    // The only background the design pulls well off centre.
    crop: { objectPosition: "53% 34%" },
  },
  {
    name: "Leonardo Da Vinci Immersive Exhibition",
    tag: ["End-to-end Event Delivery"],
    img: asset("/assets/work-leonardo-da-vinci.jpg"),
    logo: asset("/assets/client-leonaro-da-vinci.png"),
    logoWidth: 150,
    logoHeight: 68,
  },
];
