import { asset } from "@/components/Primitives";

export const WORK = [
  {
    name: "Good Things Festival",
    tag: ["BOH Management, Nationwide", "Retail Precinct Management"],
    img: asset("/assets/work-good-things.webp"),
    logo: asset("/assets/client-good-things.svg"),
    logoWidth: 377,
    logoHeight: 89,
  },
  {
    name: "Happy Hour",
    tag: ["End-to-end Event Delivery, Nationwide"],
    img: asset("/assets/work-happy-hour.webp"),
    logo: asset("/assets/client-happy-hour.webp"),
    logoWidth: 321,
    logoHeight: 83,
  },
  {
    name: "Chapter",
    tag: ["End-to-end Event Delivery"],
    img: asset("/assets/work-chapter.webp"),
    logo: asset("/assets/client-chapter.webp"),
    logoWidth: 274,
    logoHeight: 185,
  },
  {
    name: "Strummingbird",
    tag: ["Artist Services, Nationwide"],
    img: asset("/assets/work-strummingbird.webp"),
    logo: asset("/assets/client-strummingbird.svg"),
    logoWidth: 324,
    logoHeight: 65,
  },
  {
    name: "Let Them Eat Cake",
    tag: ["Artist Services", "Industry Ticketing / Community Building"],
    img: asset("/assets/work-let-them-eat-cake.webp"),
    logo: asset("/assets/client-let-them-eat-cake.svg"),
    logoWidth: 321,
    logoHeight: 59,
  },
  {
    name: "Beyond The Valley",
    tag: ["Retail Precinct Management"],
    img: asset("/assets/work-beyond-the-valley.webp"),
    logo: asset("/assets/client-beyond-the-valley.svg"),
    logoWidth: 482,
    logoHeight: 65,
  },
  {
    name: "Our City Our Sound",
    tag: ["Artist Services", "Box Office", "Accreditation"],
    img: asset("/assets/work-our-city-our-sound.webp"),
    logo: asset("/assets/client-our-city-our-sound.svg"),
    logoWidth: 162,
    logoHeight: 115,
  },
  {
    name: "Pitch Music and Arts",
    tag: [
      "Industry Ticketing / Community Building",
      "Retail Precinct Management",
    ],
    img: asset("/assets/work-pitch.webp"),
    logo: asset("/assets/client-pitch.webp"),
    logoWidth: 264,
    logoHeight: 93,
  },
  {
    name: "Strawberry Fields",
    tag: ["Industry Ticketing / Community Building"],
    img: asset("/assets/work-strawberry-fields.webp"),
    logo: asset("/assets/client-strawberry-fields.webp"),
    logoWidth: 212,
    logoHeight: 137,
  },
  {
    name: "Leonardo Da Vinci Immersive Exhibition",
    tag: ["End-to-end Event Delivery"],
    img: asset("/assets/work-leonardo-da-vinci.webp"),
    logo: asset("/assets/client-leonardo-da-vinci.webp"),
    logoWidth: 253,
    logoHeight: 115,
  },
  {
    name: "Afrosoul",
    tag: ["Industry Ticketing / Community Building"],
    img: asset("/assets/work-afrosoul.webp"),
    logo: asset("/assets/client-afrosoul.svg"),
    logoWidth: 277,
    logoHeight: 77,
  },
  {
    name: "Live Nation",
    tag: ["Industry Ticketing / Community Building"],
    img: asset("/assets/work-live-nation.webp"),
    logo: asset("/assets/client-live-nation.webp"),
    logoWidth: 346,
    logoHeight: 85,
  },
  {
    name: "Astral People",
    tag: ["Industry Ticketing / Community Building"],
    img: asset("/assets/work-astral-people.webp"),
    logo: asset("/assets/client-astral-people.svg"),
    logoWidth: 180,
    logoHeight: 129,
  },
  {
    name: "S.A.S.H",
    tag: ["Artist Advancing, Nationwide"],
    img: asset("/assets/work-sash.webp"),
    logo: asset("/assets/client-sash.svg"),
    logoWidth: 281,
    logoHeight: 67,
  },
  {
    name: "A3 Festival",
    tag: [
      "Artist Services",
      "Volunteer Management",
      "Front Gate Management",
      "Box Office Management",
      "Accreditation",
    ],
    img: asset("/assets/work-a3.webp"),
    logo: asset("/assets/client-a3.webp"),
    logoWidth: 273,
    logoHeight: 57,
  },
  {
    name: "Promiseland",
    tag: [
      "Artist Services",
      "Industry Ticketing / Community Building",
      "Retail Precinct Management",
    ],
    img: asset("/assets/work-promiseland.webp"),
    logo: asset("/assets/client-promiseland.webp"),
    logoWidth: 184,
    logoHeight: 161,
  },
  {
    name: "Eden Festival (NZ)",
    tag: ["Artist Services"],
    img: asset("/assets/work-eden-fest.webp"),
    logo: asset("/assets/client-eden-fest.webp"),
    logoWidth: 219,
    logoHeight: 139,
  },
  {
    name: "Souled Out",
    tag: [
      "Artist Services, Nationwide",
      "Industry Ticketing / Community Building",
    ],
    img: asset("/assets/work-souled-out.webp"),
    logo: asset("/assets/client-souled-out.webp"),
    logoWidth: 275,
    logoHeight: 125,
  },
  {
    name: "Knotfest",
    tag: ["BOH Management, Nationwide"],
    img: asset("/assets/work-knotfest.webp"),
    logo: asset("/assets/client-knotfest.webp"),
    logoWidth: 334,
    logoHeight: 45,
  },
];
