// @ts-nocheck
// Generated by scripts/build-framer.mjs — do not edit. Edit the source and
// re-run `pnpm build-framer`, then paste this into Framer.
//
// Plain JavaScript in a .tsx file, because Framer's code editor only makes
// .tsx. Nothing here is typed, and the imports resolve inside Framer rather
// than in this repo, so the checker has nothing useful to say about it.
//
//   components/About/About.jsx
//   components/About/StatCounter.jsx
//   framer/extra/About.tsx  (Framer only)
//
// Paste Primitives.tsx and GlobalStylesheet.tsx before this one.

import { addPropertyControls, ControlType } from "framer";
import { useEffect, useRef } from "react";
import {
  animate,
  motion,
  useInView,
  useMotionValue,
  useReducedMotion,
  useTransform,
} from "framer-motion";
import {
  styles,
  Section,
  Heading2,
  Heading4,
  TextXXLarge,
  EASE,
} from "./Primitives.tsx";

// Read as the parameter defaults here and as `defaultValue` on the Framer
// controls, the same way Hosts does it. `body` is one textarea, one line per
// paragraph, so it is written the way it reads in the panel.
const DEFAULTS = {
  heading: "Who we are",
  body: `A dream team of doers and difference-makers. Sharp, reliable and here to get it done. Each member brings something different to the table: creative brains, logistical minds, artist wranglers and on-ground weapons.

We work with grit, good humour and zero ego. We're just here to make it Happen.`,
};

/**
 * Width fills whatever it is dropped into; height is measured from the rendered
 * content, so the stylesheet decides it rather than a number typed in Framer.
 *
 * @framerSupportedLayoutWidth any
 * @framerSupportedLayoutHeight auto
 */
export default function About({
  heading = DEFAULTS.heading,
  body = DEFAULTS.body,
}) {
  return (
    <Section id="a-about">
      <div className={styles.aboutSurface}>
        <Heading2 className={styles.aboutTitle}>{heading}</Heading2>

        <TextXXLarge className={styles.aboutCopy}>{body}</TextXXLarge>

        <div className={styles.aboutStat}>
          <StatCounter
            value={10}
            suffix="+"
            className={styles.aboutStatNumber}
          />
          <Heading4 as="p" className={styles.aboutStatLabel}>
            Years doing the work
          </Heading4>
        </div>
      </div>
    </Section>
  );
}

/* ---------------------------------------------------------------------------
   components/About/StatCounter.jsx
   --------------------------------------------------------------------------- */

// Counts up from 0 to `value` each time it scrolls into view (re-triggers, like
// the other reveals in the site).
function StatCounter({ value, suffix = "", duration = 1.8, className }) {
  const ref = useRef(null);
  const inView = useInView(ref, { amount: 0.6, margin: "0px 0px -60px 0px" });
  const reduceMotion = useReducedMotion();

  const count = useMotionValue(value);
  const text = useTransform(count, (n) => Math.round(n) + suffix);

  useEffect(() => {
    if (reduceMotion) {
      count.set(value);
      return;
    }
    if (!inView) {
      count.set(0);
      return;
    }
    const controls = animate(count, value, { duration, ease: EASE });
    return () => controls.stop();
  }, [inView, reduceMotion, value, duration, count]);

  return (
    <motion.span ref={ref} className={className}>
      {text}
    </motion.span>
  );
}

/* ---------------------------------------------------------------------------
   framer/extra/About.tsx — Framer only
   --------------------------------------------------------------------------- */

// Appended to framer/About.tsx by scripts/build-framer.mjs. The defaults are
// read from the same DEFAULTS the component destructures, so the panel and an
// unconfigured instance can never disagree.
addPropertyControls(About, {
  heading: {
    type: ControlType.String,
    title: "Heading",
    defaultValue: DEFAULTS.heading,
  },
  body: {
    type: ControlType.String,
    title: "Body",
    defaultValue: DEFAULTS.body,
    displayTextArea: true,
    description: "One paragraph per line.",
  },
});
