// @ts-nocheck
// Generated by scripts/build-framer.mjs — do not edit. Edit the source and
// re-run `pnpm build-framer`, then paste this into Framer.
//
// Plain JavaScript in a .tsx file, because Framer's code editor only makes
// .tsx. Nothing here is typed, and the imports resolve inside Framer rather
// than in this repo, so the checker has nothing useful to say about it.
//
//   components/Contact/data.js
//   components/Contact/Contact.jsx
//   components/Contact/Acknowledgement.jsx
//   components/Contact/ContactForm.jsx
//
// Paste Primitives.tsx and GlobalStylesheet.tsx before this one.

import {
  styles,
  SOCIALS,
  Section,
  Heading3,
  TextMedium,
  TextSmall,
  ButtonOutlineMedium,
} from "./Primitives.tsx";

/* ---------------------------------------------------------------------------
   components/Contact/data.js
   --------------------------------------------------------------------------- */

const CONTACT_EMAILS = ["hello@happengroup.com.au"];

// Rendered as label + input pairs; `rows` marks the one multi-line field.
const FORM_FIELDS = [
  { name: "name", label: "Name", type: "text", autoComplete: "name" },
  { name: "email", label: "Email", type: "email", autoComplete: "email" },
  { name: "phone", label: "Phone number", type: "tel", autoComplete: "tel" },
  { name: "message", label: "Message", rows: 3 },
];

/**
 * Width fills whatever it is dropped into; height is measured from the rendered
 * content, so the stylesheet decides it rather than a number typed in Framer.
 *
 * @framerSupportedLayoutWidth any
 * @framerSupportedLayoutHeight auto
 */
export default function Contact() {
  return (
    <Section as="footer" id="a-contact" className={styles.contactSection}>
      <div className={styles.contactContent}>
        <div className={styles.contactHeader}>
          <Heading3 as="h2" className={styles.contactTitle}>
            Let&apos;s make it Happen
          </Heading3>
          <TextMedium className={styles.contactIntro}>
            Got a festival to run? A retail precinct to fill? An artist{" "}
            <br className="desktop-only" />
            who needs looking after? Tell us what you need.
          </TextMedium>
        </div>

        <div className={styles.contactBody}>
          <div className={styles.contactCard}>
            <span className={styles.contactCardLabel}>General enquiries</span>
            {CONTACT_EMAILS.map((email) => (
              <a
                key={email}
                className={styles.contactEmail}
                href={`mailto:${email}`}
              >
                {email}
              </a>
            ))}
            <div className={styles.contactSocials}>
              {SOCIALS.map((social) => (
                <a
                  key={social.label}
                  href={social.href}
                  target="_blank"
                  rel="noopener noreferrer"
                  aria-label={social.label}
                >
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src={social.icon}
                    alt=""
                    className={styles.contactSocialIcon}
                  />
                </a>
              ))}
            </div>
          </div>

          <ContactForm />
        </div>

        <Acknowledgement />
      </div>
    </Section>
  );
}

/* ---------------------------------------------------------------------------
   components/Contact/Acknowledgement.jsx
   --------------------------------------------------------------------------- */

function Acknowledgement() {
  return (
    <div className={styles.acknowledgement}>
      <TextSmall className={styles.acknowledgementText}>
        Happen Group acknowledges the Wurundjeri people of the Kulin Nation, the
        Traditional Owners of the land on which we are based in Naarm. We pay
        our respects to Elders past and present and acknowledge the Traditional
        Owners of the lands on which we work and gather.
      </TextSmall>
    </div>
  );
}

/* ---------------------------------------------------------------------------
   components/Contact/ContactForm.jsx
   --------------------------------------------------------------------------- */

// TODO: not wired to anything yet — there is no endpoint for it to post to, so
// submitting is swallowed rather than reloading the page with the answers in
// the query string. Point this at a form service or a route handler.
function ContactForm() {
  return (
    <form className={styles.contactForm} onSubmit={(event) => event.preventDefault()}>
      <span className={styles.contactCardLabel}>Contact form</span>

      {FORM_FIELDS.map((field) => (
        <div key={field.name} className={styles.contactField}>
          <label
            className={styles.contactFieldLabel}
            htmlFor={`contact-${field.name}`}
          >
            {field.label}
          </label>
          {field.rows ? (
            <textarea
              id={`contact-${field.name}`}
              name={field.name}
              rows={field.rows}
              className={`${styles.contactInput} ${styles.contactTextarea}`}
            />
          ) : (
            <input
              id={`contact-${field.name}`}
              name={field.name}
              type={field.type}
              autoComplete={field.autoComplete}
              className={styles.contactInput}
            />
          )}
        </div>
      ))}

      <ButtonOutlineMedium type="submit" className={styles.contactSubmit}>
        Send message
      </ButtonOutlineMedium>
    </form>
  );
}
