// @ts-nocheck
// Generated by scripts/build-framer.mjs — do not edit. Edit the source and
// re-run `pnpm build-framer`, then paste this into Framer.
//
// Plain JavaScript in a .tsx file, because Framer's code editor only makes
// .tsx. Nothing here is typed, and the imports resolve inside Framer rather
// than in this repo, so the checker has nothing useful to say about it.
//
//   components/Events/data.js
//   components/Events/Events.jsx
//
// Paste Primitives.tsx and GlobalStylesheet.tsx before this one.

import {
  styles,
  asset,
  Section,
  Heading2,
  Heading4,
  TextSmall,
  TextMedium,
  ButtonOutlineMedium,
  Badge,
  Reveal,
} from "./Primitives.tsx";

/* ---------------------------------------------------------------------------
   components/Events/data.js
   --------------------------------------------------------------------------- */

const EVENTS = [
  {
    title: "Danny Rants Off TheRecord",
    status: "upcoming",
    date: "October 2026",
    description:
      "This October I speak to Sport Stars, Celebs, DJs, Gangsters & Nightlife Icons OFF THE RECORD",
    cta: "Pre register",
    link: "https://happengroup.fillout.com/dannyrants",
    img: asset("/assets/event-off-the-record.webp"),
  },
  {
    title: "Chapter NYE 2026",
    status: "upcoming",
    date: "31st December 2026",
    description:
      "We've got big plans for NYE 2026! Sign up to be the first to hear exclusive news about Chapter NYE 2026.",
    cta: "Pre register",
    link: "https://happengroup.fillout.com/t/fQhTFKa2Ntus",
    img: asset("/assets/event-chapter-nye.webp"),
  },
  {
    title: "Unboxed Party Girl Up Late",
    status: "upcoming",
    date: "19th December 2026",
    description:
      "When the after party is the main event. Secret lineup, no guest announcement and no chance of this being a regular event",
    cta: "Join the ballot",
    link: "https://m.moshtix.com.au/v2/event/unboxed-party-girl-up-late/200244?skin=UNBOXEDMELB",
    img: asset("/assets/event-unboxed.webp"),
  },
  {
    title: "Sound Collective",
    status: "upcoming",
    date: "20th February 2027",
    description: "Reggae Island Vibes are coming to Gold Coast.",
    cta: "Tickets on sale",
    link: "https://megatix.com.au/events/sound-collective",
    img: asset("/assets/event-sound-collective.webp"),
  },
  // Example cards for testing the wrap - remove before shipping
  // {
  //   title: "P★rty Girl Tour Forgotten Cities",
  //   status: "onsale",
  //   date: "5th September 2026",
  //   description:
  //     "Lucy & Nikki's 'P★rty Girl Tour' hits Adelaide and Auckland this September. Their only live shows of the year.",
  //   cta: "Get tickets",
  //   link: "https://www.ticketmaster.com.au/party-girl-tour-forgotten-cities-presented-torrensville-05-09-2026/event/130064E68D62206C",
  //   img: asset("/assets/event-party-girl-adelaide.webp"),
  // },
  // {
  //   title: "P★rty Girl Tour Forgotten Cities",
  //   status: "soldout",
  //   date: "9th September 2026",
  //   description:
  //     "Lucy & Nikki's 'P★rty Girl Tour' hits Adelaide and Auckland this September. Their only live shows of the year.",
  //   cta: "Get tickets",
  //   link: "https://www.ticketmaster.co.nz/party-girl-tour-forgotten-cities-presented-auckland-09-09-2026/event/240064DDB8FD1EF4?currency-locale=en-au",
  //   img: asset("/assets/event-party-girl-auckland.webp"),
  // },
];

/**
 * Width fills whatever it is dropped into; height is measured from the rendered
 * content, so the stylesheet decides it rather than a number typed in Framer.
 *
 * @framerSupportedLayoutWidth any
 * @framerSupportedLayoutHeight auto
 */
export default function Events() {
  return (
    <Section
      id="a-events"
      className={styles.eventsSection}
      innerClassName={styles.eventsInner}
    >
      <Heading2 className={styles.eventsHeading}>What&apos;s Happening</Heading2>
      <div className={styles.eventsScroller}>
        {EVENTS.map((event, i) => (
          <Reveal
            key={i}
            className={styles.eventsCardWrap}
            once={true}
            amount={0}
            delay={i * 130}
          >
            <EventCard event={event} />
          </Reveal>
        ))}
      </div>
    </Section>
  );
}

const STATUSES = {
  upcoming: { label: "Upcoming", color: "charcoal" },
  onsale: { label: "On sale", color: "orange" },
  soldout: { label: "Sold out", color: "red", soldout: true },
};

function EventCard({ event }) {
  const { label, color, soldout } = STATUSES[event.status];

  return (
    <article className={styles.eventsCard}>
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={event.img}
        alt=""
        className={styles.eventsImage}
        style={event.crop}
        loading="lazy"
      />

      <div className={styles.eventsOverlay}>
        {label && <Badge color={color}>{label}</Badge>}

        <div className={styles.eventsMeta}>
          <TextSmall className={styles.eventsDate}>{event.date}</TextSmall>
          <Heading4 as="h3" className={styles.eventsTitle}>
            {event.title}
          </Heading4>
        </div>

        <TextMedium className={styles.eventsDescription}>
          {event.description}
        </TextMedium>

        <ButtonOutlineMedium
          href={event.link}
          rel="noopener noreferrer"
          target="_blank"
          className={soldout ? styles.eventsCtaSoldOut : undefined}
          aria-disabled={soldout || undefined}
        >
          {soldout ? "Sold out" : event.cta}
        </ButtonOutlineMedium>
      </div>
    </article>
  );
}
