// @ts-nocheck
// Generated by scripts/build-framer.mjs — do not edit. Edit the source and
// re-run `pnpm build-framer`, then paste this into Framer.
//
// Plain JavaScript in a .tsx file, because Framer's code editor only makes
// .tsx. Nothing here is typed, and the imports resolve inside Framer rather
// than in this repo, so the checker has nothing useful to say about it.
//
//   components/Hero/Hero.jsx
//   components/Hero/RollingLogo.jsx
//   components/Hero/TrustedBy.jsx
//
// Paste Primitives.tsx and GlobalStylesheet.tsx before this one.

import { useRef } from "react";
import { motion, useScroll, useTransform, useSpring } from "framer-motion";
import { VideoBackground } from "./VideoBackground.tsx";
import {
  styles,
  Section,
  Heading1,
  TextXXLarge,
  ButtonLarge,
  ButtonOutlineLarge,
  asset,
} from "./Primitives.tsx";

/**
 * Width fills whatever it is dropped into; height is measured from the rendered
 * content, so the stylesheet decides it rather than a number typed in Framer.
 *
 * @framerSupportedLayoutWidth any
 * @framerSupportedLayoutHeight auto
 */
export default function Hero() {
  const headerRef = useRef(null);

  return (
    <div className={styles.heroScene}>
      <VideoBackground behindNav />

      <Section
        as="header"
        id="a-hero"
        ref={headerRef}
        className={styles.heroSection}
        innerClassName={styles.heroSectionInner}
      >
        <div className={styles.heroHeadlineGroup}>
          <div className={styles.heroLogoWrap}>
            <RollingLogo trackRef={headerRef} />
          </div>
          <div>
            <Heading1 className={styles.heroHeading}>
              <span>Behind every</span>
              <span>event, is a team</span>
              <span>making it Happen</span>
            </Heading1>
          </div>
        </div>

        <div className={styles.heroCopyGroup}>
          <TextXXLarge className={styles.heroCopy}>
            We&apos;re a Melbourne-based events agency built on over 10 years of
            rolling up our sleeves and doing the work. We move fast, think
            creatively and deliver with precision.
          </TextXXLarge>
          <div className={styles.heroButtonGroup}>
            <ButtonLarge href="#a-contact">Let&apos;s talk</ButtonLarge>
            <ButtonOutlineLarge href="#b-work">See our work</ButtonOutlineLarge>
          </div>
        </div>

        <TrustedBy className={styles.heroTrusted} />
      </Section>
    </div>
  );
}

/* ---------------------------------------------------------------------------
   components/Hero/RollingLogo.jsx
   --------------------------------------------------------------------------- */

function useRoll(trackRef, logoRef) {
  const { scrollYProgress } = useScroll({
    target: trackRef,
    offset: ["start start", "end start"],
    layoutEffect: false,
  });
  const rawX = useTransform(
    scrollYProgress,
    (p) => p * (trackRef.current?.offsetWidth ?? 0),
  );
  const x = useSpring(rawX, { stiffness: 55, damping: 18, mass: 1 });
  const rotate = useTransform(
    x,
    // Guarded with 1, not 0: before mount the ref is null and this divides.
    (v) => (v / (Math.PI * (logoRef.current?.offsetWidth || 1))) * 360,
  );

  return { x, rotate };
}

function RollingLogo({ trackRef }) {
  const logoRef = useRef(null);
  const { x, rotate } = useRoll(trackRef, logoRef);

  return (
    <motion.img
      ref={logoRef}
      src={asset("/assets/logo.svg")}
      alt="Happen logo"
      className={styles.rollingLogo}
      style={{ x, rotate }}
    />
  );
}



/* ---------------------------------------------------------------------------
   components/Hero/TrustedBy.jsx
   --------------------------------------------------------------------------- */

const LOGO_SCALE = 0.3;

const CLIENTS = [
  {
    name: "Beyond The Valley",
    src: asset("/assets/client-beyond-the-valley.svg"),
    h: 65,
  },
  { name: "Live Nation", src: asset("/assets/client-live-nation.webp"), h: 85 },
  { name: "Novel", src: asset("/assets/client-novel.webp"), h: 65 },
  { name: "Happy Hour", src: asset("/assets/client-happy-hour.webp"), h: 83 },

  { name: "Dangerous Goods", src: asset("/assets/client-dg.webp"), h: 85 },
  { name: "A3", src: asset("/assets/client-a3.webp"), h: 57 },
  {
    name: "Astral People",
    src: asset("/assets/client-astral-people.svg"),
    h: 129,
  },
  {
    name: "Strawberry Fields",
    src: asset("/assets/client-strawberry-fields.webp"),
    h: 137,
  },
  { name: "Pitch", src: asset("/assets/client-pitch.webp"), h: 93 },
  {
    name: "Destroy All Lines",
    src: asset("/assets/client-destroy-all-lines.svg"),
    h: 87,
  },
  { name: "S.A.S.H", src: asset("/assets/client-sash.svg"), h: 67 },
  {
    name: "Strummingbird",
    src: asset("/assets/client-strummingbird.svg"),
    h: 65,
  },
  {
    name: "Our City Our Sound",
    src: asset("/assets/client-our-city-our-sound.svg"),
    h: 115,
  },
  { name: "Chapter", src: asset("/assets/client-chapter.webp"), h: 185 },
  { name: "Afrosoul", src: asset("/assets/client-afrosoul.svg"), h: 77 },
];

function TrustedBy({ className, ...rest }) {
  const loop = CLIENTS.concat(CLIENTS);

  return (
    <div className={`${styles.trustedByMask} ${className ?? ""}`} {...rest}>
      <div className={styles.trustedByTrack}>
        {loop.map((c, i) => (
          <div className={styles.trustedByItem} key={i} title={c.name}>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={c.src}
              alt={c.name}
              style={{ height: c.h * LOGO_SCALE }}
              className={styles.trustedByLogo}
            />
          </div>
        ))}
      </div>
    </div>
  );
}


