// @ts-nocheck
// Generated by scripts/build-framer.mjs — do not edit. Edit the source and
// re-run `pnpm build-framer`, then paste this into Framer.
//
// Plain JavaScript in a .tsx file, because Framer's code editor only makes
// .tsx. Nothing here is typed, and the imports resolve inside Framer rather
// than in this repo, so the checker has nothing useful to say about it.
//
//   components/Instagram/Instagram.jsx
//   components/Instagram/EmbedSocialFeed.jsx
//
// Paste Primitives.tsx and GlobalStylesheet.tsx before this one.

import { RenderTarget } from "framer";
import { useEffect } from "react";
import { styles, SOCIALS, Section, Heading3 } from "./Primitives.tsx";

const EMBED_REF = "e509db0b81e805a0eb40ae1c420701e728ec2ee0";

/**
 * Width fills whatever it is dropped into; height is measured from the rendered
 * content, so the stylesheet decides it rather than a number typed in Framer.
 *
 * @framerSupportedLayoutWidth any
 * @framerSupportedLayoutHeight auto
 */
export default function Instagram() {
  return (
    <Section id="a-instagram" className={styles.instagramSection}>
      <div className={styles.instagramContent}>
        <Heading3 style={{ color: "var(--color-white)" }}>Instagram</Heading3>

        <EmbedSocialFeed embedRef={EMBED_REF} />

        <div className={styles.instagramSocial}>
          <span className={styles.instagramFollowLabel}>Follow us</span>
          <div className={styles.instagramSocialLinks}>
            {SOCIALS.map((social) => (
              <a
                key={social.label}
                className={styles.instagramSocialLink}
                href={social.href}
                target="_blank"
                rel="noopener noreferrer"
              >
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={social.icon}
                  alt=""
                  className={styles.instagramSocialIcon}
                />
                {social.label}
              </a>
            ))}
          </div>
        </div>
      </div>
    </Section>
  );
}

/* ---------------------------------------------------------------------------
   components/Instagram/EmbedSocialFeed.jsx
   --------------------------------------------------------------------------- */

const SCRIPT_ID = "EmbedSocialHashtagScript";
const SCRIPT_SRC = "https://embedsocial.com/cdn/ht.js";

// ht.js marks each feed element as it renders into it, so a remounted div is
// only filled if the script runs again — hence the re-append rather than the
// vendor snippet's "already there, do nothing" guard.
function EmbedSocialFeed({ embedRef, className }) {
  // On the Framer canvas document.head is the editor's own, so loading the
  // vendor script there would run a third-party embed inside the editor on
  // every render. .feed reserves 320px and a charcoal background, so the space
  // is held either way. `framer` resolves to lib/framer-render-target.js
  // outside Framer, which always answers preview, so the feed always loads in
  // the Next app.
  const onCanvas = RenderTarget.current() === RenderTarget.canvas;

  useEffect(() => {
    if (onCanvas) return;
    document.getElementById(SCRIPT_ID)?.remove();

    const script = document.createElement("script");
    script.id = SCRIPT_ID;
    script.src = SCRIPT_SRC;
    script.async = true;
    document.head.appendChild(script);
  }, [embedRef, onCanvas]);

  return (
    <div
      className={`embedsocial-hashtag ${styles.feed} ${className ?? ""}`}
      data-ref={embedRef}
      data-dynamicload="yes"
      data-lazyload="yes"
    />
  );
}


