// @ts-nocheck
// Generated by scripts/build-framer.mjs — do not edit. Edit the source and
// re-run `pnpm build-framer`, then paste this into Framer.
//
// Plain JavaScript in a .tsx file, because Framer's code editor only makes
// .tsx. Nothing here is typed, and the imports resolve inside Framer rather
// than in this repo, so the checker has nothing useful to say about it.
//
//   components/Services/data.js
//   components/Services/Services.jsx
//
// Paste Primitives.tsx and GlobalStylesheet.tsx before this one.

import { useCallback, useEffect, useRef, useState } from "react";
import { cubicBezier, motion, useScroll, useTransform } from "framer-motion";
import {
  styles,
  asset,
  Section,
  Heading2,
  Heading3,
  TextMedium,
  useIsoLayoutEffect,
} from "./Primitives.tsx";

/* ---------------------------------------------------------------------------
   components/Services/data.js
   --------------------------------------------------------------------------- */

const DEFAULT_IMG = asset("/assets/svc-default.webp");

const SERVICES = [
  {
    title: "Artist Services",
    meta: "Plan · Host · Manage · Deliver",
    desc: "We work alongside promoters and venues, delivering artist liaison, touring support and hospitality at the highest level. From compounds and dressing rooms to communal spaces, every artist and crew member is taken care of, so promoters can focus on delivering a great event.",
    img: asset("/assets/svc-artist-services.webp"),
  },
  {
    title: "Artist Management",
    meta: "Book · Negotiate · Contract · Confirm",
    desc: "The paperwork is just as important as the performance. We handle offers, routing, contracts, deposits and lock-ins so our artists can focus on making dance floors hum.",
    img: asset("/assets/svc-artist-management.webp"),
  },
  {
    title: "Artist Tour Logistics",
    meta: "Advance · Book · Move · Track",
    desc: "Getting people where they need to be, when they need to be there. Flights, accommodation, transfers, visas and per diems. All in. All sorted.",
    img: asset("/assets/svc-artist-tour-logistics.webp"),
  },
  {
    title: "Industry Ticketing & Community Building",
    meta: "Recruit · Activate · Track · Amplify",
    desc: "Real people sell the most tickets. We build and manage teams of hosts and promoters who spread the word through their personal networks. It’s the old-school street team, reimagined for today.",
    img: asset("/assets/svc-industry-ticketing.webp"),
  },
  {
    title: "Comedy & Podcast Tours",
    meta: "Program · Advance · Tour · Deliver",
    desc: "Whether you’ve got a fully planned tour or just an idea, we’ll help bring it to life. With a trusted network across Australia and New Zealand, we connect the right people, venues and logistics to get your tour on the road.",
    img: asset("/assets/svc-comedy-podcast-tours.webp"),
  },
  {
    title: "Event Staffing",
    meta: "Source · Brief · Deploy · Deliver",
    desc: "Great events start with great staff. Tap into our trusted network of experienced professionals, built over years of working in events across Australia & New Zealand.",
    img: asset("/assets/svc-event-staffing.webp"),
  },
  {
    title: "Retail Precinct",
    meta: "Source · Curate · Build · Operate · Remit",
    desc: "Drawing on our wide network of vendors, we handle the whole process. We source the right mix of traders, vet every application, design the retail offering, manage operations on event day and settle the accounts once it’s all wrapped up.",
    img: asset("/assets/svc-retail-precinct.webp"),
  },
  {
    title: "Venue Bookings",
    meta: "Connect · Pair · Program · Deliver",
    desc: "We’ll take your idea to a dancefloor. Matching the right space to the right crowd via deep industry relationships across the Australian music scene.",
    img: asset("/assets/svc-venue-bookings.webp"),
  },
  {
    title: "Wellness & Activations",
    meta: "Design · Curate · Build · Staff · Operate",
    desc: "We curate purpose-built spaces within festivals. Our team design and deliver wellness, connection and entertainment experiences tailored to your audience.",
    img: asset("/assets/svc-wellness-activations.webp"),
  },
];

const debugFocusLine = false;
const mobileItemGap = 24;

// Which edge of the card counts as "current", and which edge of a title has
// to cross it. Desktop reads titles beside the card, so a title takes over at
// the card's bottom edge; mobile reads them over the card, so it's the card's
// top edge and the title's bottom.
const focusLine = (cardEl) => {
  const card = cardEl?.getBoundingClientRect();
  const fallback = window.innerHeight / 2;
  if (window.matchMedia("(min-width: 1024px)").matches) {
    return {
      at: card ? card.bottom : fallback,
      edgeOf: (el) => {
        const r = el.getBoundingClientRect();
        return r.top + r.height / 2;
      },
    };
  }
  return {
    at: card ? card.top : fallback,
    edgeOf: (el) => el.firstElementChild.getBoundingClientRect().bottom,
  };
};

/**
 * Width fills whatever it is dropped into; height is measured from the rendered
 * content, so the stylesheet decides it rather than a number typed in Framer.
 *
 * @framerSupportedLayoutWidth any
 * @framerSupportedLayoutHeight auto
 */
export default function Services() {
  const sectionRef = useRef(null);
  const itemRefs = useRef([]);
  const cardRef = useRef(null);
  const debugLineRef = useRef(null);
  const [active, setActive] = useState(-1);

  // Track the section's scroll progress while the section is sticky
  const { scrollYProgress } = useScroll({
    target: sectionRef,
    offset: ["start start", "end end"],
  });

  // Ease the growth of the cream surface, so it doesn't slam into the viewport edges
  const easedProgress = useTransform(scrollYProgress, [0, 1], [0, 1], {
    ease: cubicBezier(0.45, 0, 0.55, 1),
  });

  const sync = useCallback(() => {
    const { at, edgeOf } = focusLine(cardRef.current);

    if (debugFocusLine && debugLineRef.current)
      debugLineRef.current.style.top = `${at}px`;

    // Last item to have crossed the line, not the nearest one — nearest flips
    // at the midpoint between titles, well before the line.
    let next = -1;
    itemRefs.current.forEach((node, i) => {
      if (node && edgeOf(node) <= at) next = i;
    });
    setActive((prev) => (prev === next ? prev : next));
  }, []);

  useEffect(() => {
    window.addEventListener("scroll", sync, { passive: true });
    window.addEventListener("resize", sync, { passive: true });
    return () => {
      window.removeEventListener("scroll", sync);
      window.removeEventListener("resize", sync);
    };
  }, [sync]);

  useIsoLayoutEffect(sync, [sync]);

  // Past the focus line, so the clicked service is the current one: centred on
  // the card on desktop, sat fully above it on mobile
  const scrollToItem = (e) => {
    const card = cardRef.current.getBoundingClientRect();
    const item = e.currentTarget.getBoundingClientRect();
    const top = window.matchMedia("(min-width: 1024px)").matches
      ? item.top + item.height / 2 - (card.top + card.height / 2)
      : item.bottom + mobileItemGap - card.top;
    window.scrollBy({ top, behavior: "smooth" });
  };

  return (
    <Section
      as={motion.section}
      id="a-services"
      ref={sectionRef}
      className={styles.servicesSection}
      innerClassName={styles.servicesInner}
      style={{
        "--progress": easedProgress,
      }}
    >
      <div className={styles.servicesSurfaceLayer} aria-hidden>
        <div className={styles.servicesSurface} />
      </div>

      <div className={styles.servicesContentGroup}>
        <div className={styles.servicesHead}>
          <Heading2 className={styles.servicesHeading}>
            How we make it Happen
          </Heading2>
          <TextMedium className={styles.servicesCopy}>
            We&rsquo;ve built a broad operational capability and a national
            network to match.
          </TextMedium>
        </div>

        <div className={styles.servicesList}>
          {SERVICES.map((service, i) => (
            <button
              key={service.title}
              type="button"
              ref={(el) => (itemRefs.current[i] = el)}
              onClick={scrollToItem}
              className={styles.servicesListItem}
              data-active={i === active ? "" : undefined}
            >
              <Heading3 as="span" sentence>
                {service.title}
              </Heading3>
              <TextMedium className={styles.servicesListMeta}>
                {service.meta}
              </TextMedium>
              <TextMedium as="span" className={styles.servicesListDesc}>
                {service.desc}
              </TextMedium>
            </button>
          ))}
        </div>
      </div>

      <div className={styles.servicesCardLayer} aria-hidden>
        <div className={styles.servicesCardSticky}>
          <div className={styles.servicesCard} ref={cardRef}>
            <div
              className={styles.servicesSlide}
              data-active={active === -1 ? "" : undefined}
            >
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={DEFAULT_IMG}
                alt=""
                className={styles.servicesSlideImage}
              />
            </div>
            {SERVICES.map((service, i) => (
              <div
                key={service.title}
                className={styles.servicesSlide}
                data-active={i === active ? "" : undefined}
              >
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={service.img}
                  srcSet={`${service.img.replace(/\.webp$/, "-mobile.webp")} 800w, ${service.img} 950w`}
                  sizes="(min-width: 1024px) 600px, min(100vw, 400px)"
                  alt=""
                  className={styles.servicesSlideImage}
                  loading="lazy"
                />
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* DEBUG: focus line */}
      {debugFocusLine && (
        <div
          ref={debugLineRef}
          aria-hidden
          style={{
            position: "fixed",
            left: 0,
            right: 0,
            height: "2px",
            background: "limegreen",
            zIndex: 9999,
            pointerEvents: "none",
          }}
        />
      )}
    </Section>
  );
}
