// @ts-nocheck
// Generated by scripts/build-framer.mjs — do not edit. Edit the source and
// re-run `pnpm build-framer`, then paste this into Framer.
//
// Plain JavaScript in a .tsx file, because Framer's code editor only makes
// .tsx. Nothing here is typed, and the imports resolve inside Framer rather
// than in this repo, so the checker has nothing useful to say about it.
//
//   components/Testimonials/data.js
//   components/Testimonials/Testimonials.jsx
//   components/Testimonials/Phone.jsx
//   components/Testimonials/Thread.jsx
//
// Paste Primitives.tsx and GlobalStylesheet.tsx before this one.

import { useEffect, useRef, useState } from "react";
import { motion, useInView } from "framer-motion";
import { styles, asset, Section, Heading3, EASE } from "./Primitives.tsx";

/* ---------------------------------------------------------------------------
   components/Testimonials/data.js
   --------------------------------------------------------------------------- */

// Each entry is one message in the phone's thread. They alternate sides
// automatically — index order is the only thing that decides which way a
// bubble faces, so adding or removing one re-flows the whole thread.
//
// Avatars fall back to the generic placeholder until a real headshot comes
// through — swap each one out per person as they land.
const TESTIMONIALS = [
  {
    name: "Jeff Moss",
    role: "Sound Event Group",
    quote:
      "Collaborating with the guys from Happen Group is a pleasure. Their understanding of what is required at a festival and knowledge of site infrastructure ensures a seamless exercise. They are prepared to roll up their sleeves to get the job done and have the finesse to design exciting and dynamic spaces.",
    avatar: asset("/assets/testimonial-avatar-jeff-moss.jpg"),
  },
  {
    name: "Jacob Malmo",
    role: "Thick as Thieves",
    quote:
      "We've worked with the Happen team for years and it's been smooth sailing from day one. The care they put into their shows from sound, creative, artist experience and care is unmatched. Highly recommend.",
    avatar: asset("/assets/testimonial-avatar-jacob-malmo.webp"),
  },
  {
    name: "Daniel Hildebrand",
    role: "Astral People",
    quote:
      "Working with Happen Group has been a seamless experience from day one. Their team has helped us build meaningful community engagement through a highly effective micro-influencer campaign, while their street team has played an important role in increasing awareness and driving ticket sales for our events. They're proactive, easy to work with, and consistently deliver with professionalism and care.",
    avatar: asset("/assets/testimonial-avatar-dan-hildebrand.webp"),
  },
  {
    name: "Miranda Nicol",
    role: "Untitled Group",
    quote:
      "We've loved working with Paris and Dana at Happen Group on the retail precinct at Beyond the Valley and Pitch Music & Arts. They come to every conversation prepared, stay on top of timelines, and make the whole process feel collaborative, which is exactly what you need in the lead-up to a major festival. We always feel like our vendor relationships are in good hands.",
    avatar: asset("/assets/testimonial-avatar-miranda-nicol.webp"),
  },
  {
    name: "Mike Toner",
    role: "Thick as Thieves",
    quote:
      "I have been working with Happen Group for a number of years now, and everything from their communication, professionalism and attention to detail is top notch. They really know how to wear the hats of everyone from promoters, to punters, to site operators and everyone else, which results in a win-win for all working with them. Could not recommend highly enough.",
    avatar: asset("/assets/testimonial-avatar-mike-toner.webp"),
  },
  {
    name: "Annie Tetzlaff",
    role: "Good Things Festival / Destroy All Lines",
    quote:
      "We absolutely love working with Happen Group. Macca, Paris and the team are incredibly easy to work with, communicate well and are super organised. No matter what gets thrown at them onsite, they're calm, adaptable and just get on with it with a smile and a laugh.",
    avatar: asset("/assets/testimonial-avatar-placeholder.svg"),
  },
  {
    name: "Jerry Poon",
    role: "Director, LTEC",
    quote:
      "Working with The Happen Group for artist liaison, logistics, and artist services at the LTEC Festival was an absolute pleasure from start to finish. Their team consistently went above and beyond, anticipating needs before we even had to ask and thinking outside the box to solve challenges quickly and creatively. Every aspect of artist care and logistics was handled with efficiency and professionalism, and they maintained an exceptionally high standard throughout the entire event. Their dedication and attention to detail made a real difference to our artists' experience, and we wouldn't hesitate to work with The Happen Group again.",
    avatar: asset("/assets/testimonial-avatar-jerry-poon.jpg"),
  },
  {
    name: "Fil Palermo",
    role: "Director, Untitled Group",
    quote:
      "We have worked with the team at Happen Group for over 10 years now in a number of different roles. Whether we are contracting them to deliver an area of one of our festivals or working together on an event it is always a great experience.",
    avatar: asset("/assets/testimonial-avatar-fil-palermo.webp"),
  },
];

/**
 * Width fills whatever it is dropped into; height is measured from the rendered
 * content, so the stylesheet decides it rather than a number typed in Framer.
 *
 * @framerSupportedLayoutWidth any
 * @framerSupportedLayoutHeight auto
 */
export default function Testimonials() {
  return (
    <Section id="a-testimonials">
      <div className={styles.testimonialsSurface}>
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={asset("/assets/bg-graphic-2.webp")}
          alt=""
          className={styles.testimonialsBg}
          loading="lazy"
          decoding="async"
        />

        {/* Fades the thread out as it runs up behind the heading. Mobile only —
            on desktop the phone's own bezel does that job. */}
        <div className={styles.testimonialsScrim} aria-hidden="true" />

        <Heading3 as="h2" className={styles.testimonialsTitle}>
          Trusted by the best <br /> in the business
        </Heading3>

        <Phone>
          <Thread />
        </Phone>
      </div>
    </Section>
  );
}

/* ---------------------------------------------------------------------------
   components/Testimonials/Phone.jsx
   --------------------------------------------------------------------------- */

function Phone({ children }) {
  return (
    <div className={styles.phone}>
      <div className={styles.phoneScreen}>{children}</div>
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={asset("/assets/testimonials-phone-frame.png")}
        alt=""
        className={styles.phoneFrame}
        loading="lazy"
      />
    </div>
  );
}

/* ---------------------------------------------------------------------------
   components/Testimonials/Thread.jsx
   --------------------------------------------------------------------------- */

// Each message pops in as a typing pill, expands into the bubble, and the feed
// scrolls to keep the live one at the bottom of the screen.

// Milliseconds: pause before the first message, dots before it expands, and the
// gap between messages.
const LEAD_IN = 500;
const TYPING = 900;
const STEP = 2400;

// Breathing room under a message once scrolled into place.
const BOTTOM_INSET = 24;

const bubble = {
  hidden: { opacity: 0, scale: 0.4 },
  shown: { opacity: 1, scale: 1, transition: { duration: 0.5, ease: EASE } },
};

// A layout animation rather than a height transition, so the row is at its
// final size in the DOM and the scroll below can measure it while it opens.
const expand = { duration: 0.45, ease: EASE };

function Thread() {
  const feedRef = useRef(null);
  const rowRefs = useRef([]);
  // Last message to have expanded, and the one showing its dots; -1 is not yet.
  const [landed, setLanded] = useState(-1);
  const [typing, setTyping] = useState(-1);
  const inView = useInView(feedRef, { amount: 0.2 });
  // Once the visitor scrolls the thread themselves the messages keep arriving,
  // but the feed stops dragging itself to the newest one.
  const takenOver = useRef(false);
  const active = Math.max(landed, typing);

  // Rewinds out of view so it replays on the way back.
  useEffect(() => {
    if (!inView) {
      setLanded(-1);
      setTyping(-1);
      takenOver.current = false;
      feedRef.current?.scrollTo({ top: 0 });
      return;
    }
    // A flat timeline of two timers per message keeps the beats from drifting.
    const timers = TESTIMONIALS.flatMap((_, i) => {
      const at = LEAD_IN + i * STEP;
      return [
        setTimeout(() => setTyping(i), at),
        setTimeout(() => {
          setTyping(-1);
          setLanded(i);
        }, at + TYPING),
      ];
    });
    return () => timers.forEach(clearTimeout);
  }, [inView]);

  // Input events only, never scroll itself, which the smooth scroll below fires.
  useEffect(() => {
    const feed = feedRef.current;
    if (!feed) return;
    const takeOver = () => {
      takenOver.current = true;
    };
    feed.addEventListener("wheel", takeOver, { passive: true });
    feed.addEventListener("touchmove", takeOver, { passive: true });
    feed.addEventListener("keydown", takeOver);
    return () => {
      feed.removeEventListener("wheel", takeOver);
      feed.removeEventListener("touchmove", takeOver);
      feed.removeEventListener("keydown", takeOver);
    };
  }, []);

  // Runs on both beats: the dots arriving, then the message pushing the thread
  // down as it expands.
  useEffect(() => {
    const feed = feedRef.current;
    const row = rowRefs.current[active];
    if (active < 0 || !feed || !row || takenOver.current) return;

    // offsetTop, not a client rect: the row is still scaled down, and offsets
    // ignore transforms. It shares an offsetParent with the feed.
    const top = row.offsetTop - feed.offsetTop;
    // A message taller than the screen aligns to the top padding instead, so
    // what gets cut off is its tail rather than its opening line.
    const topInset =
      parseFloat(getComputedStyle(feed).paddingTop) || BOTTOM_INSET;
    const overflows =
      row.offsetHeight > feed.clientHeight - topInset - BOTTOM_INSET;
    const target = overflows
      ? top - topInset
      : top + row.offsetHeight - feed.clientHeight + BOTTOM_INSET;

    feed.scrollTo({ top: Math.max(0, target), behavior: "smooth" });
  }, [active, landed]);

  return (
    <ol className={styles.testimonialsFeed} ref={feedRef}>
      {TESTIMONIALS.map((item, i) => {
        // Odd entries mirror to the other side of the thread.
        const flipped = i % 2 === 1;
        return (
          <motion.li
            key={`${item.name}-${i}`}
            ref={(el) => {
              rowRefs.current[i] = el;
            }}
            className={`${styles.testimonialsRow} ${flipped ? styles.testimonialsRowFlipped : ""}`}
            variants={bubble}
            initial="hidden"
            animate={i <= active ? "shown" : "hidden"}
          >
            <motion.figure
              layout
              transition={expand}
              className={`${styles.testimonialsBubble} ${
                i > landed ? styles.testimonialsBubbleTyping : ""
              }`}
            >
              {i > landed ? (
                <span className={styles.testimonialsDots} aria-hidden="true">
                  <span className={styles.testimonialsDot} />
                  <span className={styles.testimonialsDot} />
                  <span className={styles.testimonialsDot} />
                </span>
              ) : (
                <div className={styles.testimonialsMessage}>
                  <figcaption className={styles.testimonialsAuthor}>
                    {item.name} - {item.role}
                  </figcaption>
                  <blockquote className={styles.testimonialsQuote}>{item.quote}</blockquote>
                </div>
              )}
              {/* Own layout, so the growth doesn't stretch the tail. */}
              <motion.span
                layout
                transition={expand}
                className={styles.testimonialsTail}
                aria-hidden="true"
              />
            </motion.figure>
            <motion.img
              layout
              transition={expand}
              src={item.avatar}
              alt={`${item.name}, ${item.role}`}
              className={styles.testimonialsAvatar}
              width={50}
              height={50}
              loading="lazy"
            />
          </motion.li>
        );
      })}
    </ol>
  );
}
