// @ts-nocheck
// Generated by scripts/build-framer.mjs — do not edit. Edit the source and
// re-run `pnpm build-framer`, then paste this into Framer.
//
// Plain JavaScript in a .tsx file, because Framer's code editor only makes
// .tsx. Nothing here is typed, and the imports resolve inside Framer rather
// than in this repo, so the checker has nothing useful to say about it.
//
//   components/Vendors/data.js
//   components/Vendors/Vendors.jsx
//   framer/extra/Vendors.tsx  (Framer only)
//
// Paste Primitives.tsx and GlobalStylesheet.tsx before this one.

import { addPropertyControls, ControlType } from "framer";
import {
  styles,
  asset,
  Section,
  Heading3,
  TextMedium,
  ButtonOutlineMedium,
  Reveal,
} from "./Primitives.tsx";

/* ---------------------------------------------------------------------------
   components/Vendors/data.js
   --------------------------------------------------------------------------- */

// Two fixed card slots rather than an array, for the same reason as Hosts:
// Framer's on-page editor only lists simple controls, so an Array control never
// appears there. Three is the cap anyway — a fourth scrolls the row sideways on
// desktop, which the layout was never drawn for. A slot with an empty name is
// not rendered.
const DEFAULTS = {
  heading: "Festival retail vendors",
  body: "We’re on the lookout for market stall holders to join us at the festival and help bring the space to life.",
  card1Name: "Good Things Festival",
  card1Logo: asset("/assets/client-good-things.svg"),
  card1Cta: "Get your stall",
  card1Link: "https://form.jotform.com/261311126413846",
  card2Name: "Beyond The Valley",
  card2Logo: asset("/assets/client-beyond-the-valley.svg"),
  card2Cta: "Get your stall",
  card2Link: "https://form.jotform.com/261448233625861",
};

// Between intakes. Same shell, same id, same backdrop; the card row becomes one
// card with a generic message and a CTA to an expression-of-interest form.
const CLOSED_DEFAULTS = {
  heading: DEFAULTS.heading,
  body: DEFAULTS.body,
  copy: "Register your interest and we’ll be in touch.",
  cta: "Register",
  link: "https://happengroup.fillout.com/t/kCuR3PBPduus",
};

/**
 * Width fills whatever it is dropped into; height is measured from the rendered
 * content, so the stylesheet decides it rather than a number typed in Framer.
 *
 * @framerSupportedLayoutWidth any
 * @framerSupportedLayoutHeight auto
 */
export default function Vendors(props) {
  const {
    heading = DEFAULTS.heading,
    body = DEFAULTS.body,
    newTab = true,
  } = props;
  const cards = [1, 2]
    .map((n) => ({
      name: props[`card${n}Name`] ?? DEFAULTS[`card${n}Name`],
      logo: props[`card${n}Logo`] ?? DEFAULTS[`card${n}Logo`],
      cta: props[`card${n}Cta`] ?? DEFAULTS[`card${n}Cta`],
      link: props[`card${n}Link`] ?? DEFAULTS[`card${n}Link`],
    }))
    .filter((card) => card.name);

  return (
    <VendorsSection heading={heading} body={body}>
      {cards.map((event, i) => (
        <Reveal
          key={i}
          className={styles.vendorsCardOuter}
          once={true}
          amount={0}
          delay={i * 130}
        >
          <div className={styles.vendorsCard}>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={event.logo}
              alt={event.name}
              className={styles.vendorsLogo}
              loading="lazy"
            />

            <ButtonOutlineMedium
              href={event.link}
              rel={newTab ? "noopener noreferrer" : undefined}
              target={newTab ? "_blank" : undefined}
            >
              {event.cta}
            </ButtonOutlineMedium>
          </div>
        </Reveal>
      ))}
    </VendorsSection>
  );
}

export function VendorsClosed({
  heading = CLOSED_DEFAULTS.heading,
  body = CLOSED_DEFAULTS.body,
  copy = CLOSED_DEFAULTS.copy,
  cta = CLOSED_DEFAULTS.cta,
  link = CLOSED_DEFAULTS.link,
  newTab = true,
}) {
  return (
    <VendorsSection heading={heading} body={body}>
      <Reveal className={styles.vendorsClosedCardOuter} once={true} amount={0}>
        <div className={styles.vendorsClosedCard}>
          <TextMedium className={styles.vendorsClosedCardCopy}>
            {copy}
          </TextMedium>
          <ButtonOutlineMedium
            href={link}
            rel={newTab ? "noopener noreferrer" : undefined}
            target={newTab ? "_blank" : undefined}
          >
            {cta}
          </ButtonOutlineMedium>
        </div>
      </Reveal>
    </VendorsSection>
  );
}

function VendorsSection({ heading, body, children }) {
  return (
    <Section id="a-vendors" className={styles.vendorsSection}>
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={asset("/assets/vendor-bg.webp")}
        alt=""
        className={styles.vendorsSurface}
        loading="lazy"
        decoding="async"
      />

      <div className={styles.vendorsContentGroup}>
        <div className={styles.vendorsCopy}>
          <Heading3
            as="h2"
            className={styles.vendorsHeading}
            animateTracking={false}
          >
            {heading}
          </Heading3>
          <TextMedium className={styles.vendorsBody}>{body}</TextMedium>
        </div>

        <div className={styles.vendorsCardGroup}>{children}</div>
      </div>
    </Section>
  );
}

/* ---------------------------------------------------------------------------
   framer/extra/Vendors.tsx — Framer only
   --------------------------------------------------------------------------- */

// Appended to framer/Vendors.tsx by scripts/build-framer.mjs. Both states live
// in one file because they come from one source file; VendorsClosed.tsx is a
// re-export so the instance already in the Framer page keeps resolving.
addPropertyControls(Vendors, {
  heading: {
    type: ControlType.String,
    title: "Heading",
    defaultValue: DEFAULTS.heading,
  },
  body: {
    type: ControlType.String,
    title: "Body",
    defaultValue: DEFAULTS.body,
    displayTextArea: true,
  },
  card1Name: {
    type: ControlType.String,
    title: "Card 1 name",
    defaultValue: DEFAULTS.card1Name,
    description: "Alt text for the logo. Leave empty to hide this card.",
  },
  card1Logo: {
    type: ControlType.Image,
    title: "Card 1 logo",
    defaultValue: DEFAULTS.card1Logo,
    description: "Capped at 256 × 50, and at 188 × 44 below 1200px.",
  },
  card1Cta: {
    type: ControlType.String,
    title: "Card 1 CTA",
    defaultValue: DEFAULTS.card1Cta,
  },
  card1Link: {
    type: ControlType.String,
    title: "Card 1 link",
    defaultValue: DEFAULTS.card1Link,
  },
  card2Name: {
    type: ControlType.String,
    title: "Card 2 name",
    defaultValue: DEFAULTS.card2Name,
    description: "Alt text for the logo. Leave empty to hide this card.",
  },
  card2Logo: {
    type: ControlType.Image,
    title: "Card 2 logo",
    defaultValue: DEFAULTS.card2Logo,
    description: "Capped at 256 × 50, and at 188 × 44 below 1200px.",
  },
  card2Cta: {
    type: ControlType.String,
    title: "Card 2 CTA",
    defaultValue: DEFAULTS.card2Cta,
  },
  card2Link: {
    type: ControlType.String,
    title: "Card 2 link",
    defaultValue: DEFAULTS.card2Link,
  },
  newTab: {
    type: ControlType.Boolean,
    title: "New tab",
    defaultValue: true,
  },
});

addPropertyControls(VendorsClosed, {
  heading: {
    type: ControlType.String,
    title: "Heading",
    defaultValue: CLOSED_DEFAULTS.heading,
  },
  body: {
    type: ControlType.String,
    title: "Body",
    defaultValue: CLOSED_DEFAULTS.body,
    displayTextArea: true,
  },
  copy: {
    type: ControlType.String,
    title: "Card copy",
    defaultValue: CLOSED_DEFAULTS.copy,
    displayTextArea: true,
    description: "The message in place of the event cards.",
  },
  cta: {
    type: ControlType.String,
    title: "CTA",
    defaultValue: CLOSED_DEFAULTS.cta,
  },
  link: {
    type: ControlType.Link,
    title: "Link",
    defaultValue: CLOSED_DEFAULTS.link,
    description: "The expression-of-interest form.",
  },
  newTab: {
    type: ControlType.Boolean,
    title: "New tab",
    defaultValue: true,
  },
});
